# Generated by Django 2.0.13 on 2019-03-06 23:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_chosen', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('hair', 'hair styling'), ('nails', 'nail styling'), ('makeup', 'makeup styling')], default='No Services', max_length=10), size=None)),
            ],
        ),
    ]
