# Generated by Django 2.0.13 on 2019-06-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('services', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.NullBooleanField()),
            ],
        ),
    ]
