# Generated by Django 2.0.13 on 2019-03-04 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20190303_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='user_info',
            field=models.OneToOneField(blank=True, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
