# Generated by Django 2.0.13 on 2019-03-13 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_serviceproviders_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproviders',
            name='id',
        ),
        migrations.AlterField(
            model_name='serviceproviders',
            name='user_info',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
