# Generated by Django 2.0.13 on 2019-03-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_serviceprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
