# Generated by Django 2.0.13 on 2019-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190302_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_service_provider',
            field=models.BooleanField(default=False, verbose_name='Service Provider Status'),
        ),
    ]
