# Generated by Django 2.0.13 on 2019-03-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('account', '0002_email_max_length'),
        ('users', '0007_auto_20190302_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='services_provided',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
