# Generated by Django 2.0.13 on 2019-03-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190302_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='available_services',
            new_name='name',
        ),
    ]
