# Generated by Django 2.0.13 on 2019-03-03 00:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190303_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None),
        ),
    ]
